---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgB0Bzl++CeZFjHl+moJDxnL72KrOrJa1QqzOmZS3iAdbE+1ryHAnMO0GsZ5/GZ1+aTFZrKUpv7lB+ALceBZ/tjiJ9UYC80LwxpMkQQu60PD0Q6lW3lDXdgtTcn8Gegzga8vSQUFEUCqa/12dodi/z8fhutpUVabq/Dveli7tJfpeMtaeO8BNplgJXgbbYa+nssbaAFdca9rH+AuzhfK7GNqkU3e4cDGCLRi7ioae0enAeYLHW+8Kb6KNYfjdwq57ryrd/VQPsvriWl7A2oHu0D/huhE6vQqshagrg2OcBt+zCEyQLqK6Gv8ZoXbVtnNLYldatDOb9N6iGEeTl8xlbVbtQIG/grXWNQOWSHLa3dtGMHHm5IlBovXBSxzp9oSqeC5NdByb5KyKTN6naiZnUrkPZcSz1DiCgR1YETQzxCMmWZR0vFqqRy1FyeITYymN5FaSDyI9p9hoLBlq0V+LkRN6fmLao2BeBP9l3y6lKkrr6/0bkwFOb9mK8z3LjVM7xuCDO4exSOwPhe4JjwWk+Kr74dRE2TkgRw0RZ+ZdqjNSyukz3pUkkjlBaD3yE0uag9Q+WW6GpppqxZ5WBa4kbaVCT2tsF+cbmM2VTWeTr4fBzKR4K9SMc7bwbBV+5yumSymSUodngwUYijSC21uVGUl1e3g2xu8lspAMowzL8v2Ye3dh3+ZY2yGIqMRawhXmxPtwYz2qzKHdMTTZbHqk1vaLG/5YmEzWUikJHa4XHW0pIVSTe1YAIOjA4niwvE9ChKno9TOhe0zzOu2bfn835PUWa1d7HvP0sx7az8iahrIV3CEPX0P1BlVET9YkwfI0vy1+i0viJ/eCx/wly27yaRqixgq8jPy8JynJaYiEvVTLb0MsbJkFk1Wbju1gx0sE1y2BniPezJYf/nAAhig14n9gc882uCozbW7LpdrlD2e
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
